### ISSUE TITLE
Distribuition

### ISSUE THREAD

**Issue by HackM3nt3** [NullArray/Keylogger#1]
I tried to make the logger.exe but it didn't work, i used veil-evasion to make the executable with pyinstaller/wrapper.  any suggest please.

**Comment by NullArray** [comment]
What exactly did not work? Did you have issues with compiling, recieving your logs, or what exactly? Could you please try to be a little more specific.

Thanks.

**Comment by LeoRToro** [comment]
the logs never came in, sorry for my lack of experience, but i'm quick learner, do i need to change something in my gmail account?, i already put my gmail in less secure apps. I compiled the executable using Veil-evasion, i think the libraries should worked using pyinstaller/wrapper, or do i need to use a different method to compile logger.py?

**Comment by NullArray** [comment]
Couple things. First off, i'd try to compile the script with pyinstaller alone see if that changes anything. If not, do you have an anti virus application that intercepts or blocks SMTP traffic? For instance, Avast! has this thing called MailShield which can be configured to scan incoming and outgoing mail. Try to turn this feature off in your anti virus application and see what happens.
