### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by usama7628674** [NullArray/Keylogger#10]
Don't use pythoncom and pyhook modules use keyboard module very simple and it logs all special keys.Take a look at [here](https://github.com/DarkSecDevelopers/Absorber/blob/master/Template/log.py) the keylogger I coded.

**Comment by NullArray** [comment]
Thank you for the suggestion, I already dropped the modules in favor of a new approach in my new design.

Your keylogger looks pretty good. Also, if you have any more suggestions please don't hesitate to mention them. Suggestions are always appreciated.
