### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by Lotus32** [NullArray/Keylogger#2]
Good morning,
when I compile the keylogger I get the following error code:

Traceback (most recent call last):
  File "C:\Users\Riccardo\Documents\logger.py", line 86, in <module>
    obj.KeyDown = keypressed()
TypeError: keypressed() takes exactly 1 argument (0 given)

How I can solve that? I've already installed all the needed modules.

**Comment by NullArray** [comment]
Hi Lotus thanks for mentioning the issue, on line 86 where the keypressed function is called add "event" between the parenthesis so it looks like this: obj.KeyDown = keypressed(event).

If it throws a "Global NameError: event is not defined" please let me know and i will look into it more thoroughly.
