### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by dunkelite** [NullArray/Keylogger#3]
Hello why am I getting this error? Thanks :) 
 File "C:\Users\dunkelite\Desktop\New folder (4)\Keylogger-master\logger.py", line 86, in <module>
    obj.KeyDown = keypressed()
TypeError: keypressed() takes exactly 1 argument (0 given)

**Comment by NullArray** [comment]
Hey @dunkelite could you open the main python file in a text editor and change line 86 to:
`obj.KeyDown = keypressed(event)`, save it, then run it again. 

Let me know if it works after you've done so or not. If it doesn't work i'll look into it some more. I am currently not on my main development rig so there isn't much testing i can do from my end. At least at this moment. 

Let me know how it goes!
